### ISSUE TITLE
进程问题导致日志文件报错

### ISSUE THREAD

**Issue by ChenZIDu** [RowTeam/SharpExchangeKing#4]
![image](https://github.com/RowTeam/SharpExchangeKing/assets/49174343/5cdabd5a-1267-4263-9839-3a157d6809d7)
 密码爆破那栏version可以根据info的信息自动选择吗

**Comment by RcoIl** [comment]
默认手动选择，不自动选择。顺手的事情啦。

ccc1cc ***@***.***> 于2023年5月31日周三 11:11写道：

**Comment by RcoIl** [comment]
默认手动选择，都只是顺手的事情，哈哈。后续看看自动选择吧。


至于日志文件报错，已解决。

**Comment by ChenZIDu** [comment]
ok
